In [8]:
import pandas as pd
path= r"C:\Users\Asus\Pictures\npr.csv"

In [9]:
file= pd.read_csv(path)

In [10]:
file.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [11]:
from sklearn.feature_extraction.text import CountVectorizer

In [22]:
cv= CountVectorizer(max_df= 0.9, min_df= 0.02,stop_words='english')

In [23]:
dtm=vectorized= cv.fit_transform(file['Article'])

In [24]:
dtm

<11992x2620 sparse matrix of type '<class 'numpy.int64'>'
	with 1941137 stored elements in Compressed Sparse Row format>

In [25]:
from sklearn.decomposition import LatentDirichletAllocation as LDA_

In [26]:
LDA= LDA_(n_components= 10)

In [60]:
LDA.fit(dtm)

LatentDirichletAllocation()

In [61]:
len(cv.get_feature_names())

2620

In [62]:
LDA.components_

array([[2.17201746e+03, 7.16145669e+02, 3.86043237e+02, ...,
        7.32591159e+01, 3.93029341e+00, 7.70984169e+01],
       [1.66016853e+02, 1.32657591e+02, 4.75983970e+01, ...,
        1.00058972e-01, 1.00045860e-01, 1.71277129e+01],
       [5.89223996e+02, 5.00640131e+02, 2.25184400e+02, ...,
        1.43149050e+02, 1.21473570e+02, 6.04795880e+01],
       ...,
       [1.73369883e+02, 2.79046592e+02, 3.37007394e+01, ...,
        9.06760617e+01, 5.32916571e+01, 4.37233827e+01],
       [6.87354926e+02, 5.40965304e+02, 3.05200638e+02, ...,
        5.51346023e+01, 3.21293971e+01, 7.23541413e+01],
       [7.69032470e+00, 1.76062821e+02, 5.98302458e+01, ...,
        1.63260844e+02, 1.13004834e+02, 2.31172718e+01]])

In [63]:
len(LDA.components_)

10

In [64]:
LDA.components_[0].shape

(2620,)

In [65]:
LDA.components_[0].argsort()[-10:]

array([1507, 1484, 2612, 2223, 2032, 1674, 1675,  378, 2044, 1112],
      dtype=int64)

In [66]:
LDA.components_[0].argmax()

1112

In [67]:
cv.get_feature_names()[2612]

'year'

In [68]:
for indices in LDA.components_[0].argsort()[-10:]:
    print(cv.get_feature_names()[indices])

money
million
year
state
said
people
percent
care
says
health


#### Least Common

In [69]:
for indices in LDA.components_[0].argsort()[:10]:
    print(cv.get_feature_names()[indices])

album
muslims
musical
characters
isis
songs
muslim
syrian
nomination
russian


## Hence Proved, Republicans are more popular than Democrats :}

In [70]:
for index, topics in enumerate(LDA.components_):
    print("Topic #", index)
    print("\n\n")
    
    for indices in LDA.components_[index].argsort()[-10:]:
        
        print(cv.get_feature_names()[indices])
    print("\n\n\n")

Topic # 0



money
million
year
state
said
people
percent
care
says
health




Topic # 1



told
new
fbi
investigation
npr
company
media
information
news
said




Topic # 2



like
research
health
children
university
study
students
people
school
says




Topic # 3



want
going
really
know
don
think
just
like
people
says




Topic # 4



russia
congress
senate
administration
white
obama
house
said
president
trump




Topic # 5



justice
rights
case
people
state
law
says
court
police
said




Topic # 6



north
government
according
country
china
reports
says
women
people
said




Topic # 7



sanders
election
republican
party
state
voters
campaign
said
clinton
trump




Topic # 8



water
team
just
year
like
time
world
years
new
says




Topic # 9



know
life
way
people
time
new
black
just
music
like






In [71]:
file.shape

(11992, 1)

In [72]:
dtm.shape

(11992, 2620)

In [59]:
LDA.components_.shape

(10, 2620)

In [74]:
res=LDA.transform(dtm)

In [75]:
res.shape

(11992, 10)

In [78]:
res.argsort()


array([[9, 2, 3, ..., 7, 1, 4],
       [2, 0, 5, ..., 1, 6, 4],
       [0, 2, 9, ..., 7, 1, 4],
       ...,
       [4, 1, 0, ..., 6, 2, 8],
       [8, 0, 2, ..., 9, 4, 7],
       [1, 2, 4, ..., 3, 7, 6]], dtype=int64)

In [83]:
res[0].round(2).argsort()[-1]

4

In [82]:
res[0].round(2)

array([0.01, 0.15, 0.  , 0.  , 0.71, 0.02, 0.02, 0.07, 0.03, 0.  ])

In [84]:
label=[]
for i in range(res.shape[0]):
    label.append(res[i].round(2).argsort()[-1])
    

In [86]:
label= [x+1 for x in label]

In [87]:
file['Topic']= label

In [89]:
file.tail()

Article  Topic
11987  The number of law enforcement officers shot an...      6
11988    Trump is busy these days with victory tours,...      5
11989  It’s always interesting for the Goats and Soda...      9
11990  The election of Donald Trump was a surprise to...      8
11991  Voters in the English city of Sunderland did s...      7